### ISSUE TITLE
Remove "Scratch" from names?

### ISSUE THREAD

**Issue by IronManMark20** [NoMod-Programming/Whiskers-2.8#1]
Don't you have to remove the name "Scratch" from files distributed in a Scratch mod?

**Comment by NoMod-Programming** [comment]
Looks like I was just lazy and copied the files over onto here. I will update the repository within a few hours.

**Comment by NoMod-Programming** [comment]
Okay fixed it :package:

**Comment by IronManMark20** [comment]
Cool!

**Comment by IronManMark20** [comment]
Not to be that guy, but I think you also need to rename ScratchPlugin.dll and the ScratchSkin folder. (also the .dll shows up in NuWhiskers). :smile:

**Comment by NoMod-Programming** [comment]
I'll see what I can do about renaming these. The ScratchSkin folder can be renamed, but the ScratchPlugin.dll might have some hooks based on its name.
