### ISSUE TITLE
"About" should load a webpage.

### ISSUE THREAD

**Issue by Radical-from-Scratch** [NoMod-Programming/Whiskers-2.8#15]
It doesn't have to be the same one as in Scratch, it just doesn't feel right to have a dialog box.

**Comment by NoMod-Programming** [comment]
Hmm... I'll have to think about this.

**Comment by Radical-from-Scratch** [comment]
We can create a website using just github. Just make a repo called "whiskers.github.io" or something

**Comment by NoMod-Programming** [comment]
I know, but I have [whiskers.gwiddle.co.uk](whiskers.gwiddle.co.uk)

**Comment by Radical-from-Scratch** [comment]
OK, that's cool, but then the website will have a different copy than the repo ( I was hoping the website files could BE a repo). But it's not *that* big a deal, the Gwiddle one will work just fine.

**Comment by Jonathan50** [comment]
...or, like in Scratch 1.x, in the Share menu there should be a 'Go to Whiskers site' option...

**Comment by Radical-from-Scratch** [comment]
When it's my turn to make changes again, I am going to make it so that the "upload to website" option in file menu goes to the whiskers site.

**Comment by Jonathan50** [comment]
Why...?
