### ISSUE TITLE
paint editor should not require a button

### ISSUE THREAD

**Issue by Radical-from-Scratch** [NoMod-Programming/Whiskers-2.8#17]
In Scratch, clicking on a costume immediately loads the paint editor. In Whiskers, it's still the 1.4 method. I could do *part* of this, but I'm not gonna start something I can't finish. Could you look into it, NoMod?

**Comment by NoMod-Programming** [comment]
I'm still working on the paint editor (The code for it is nearly done, I just need to add options)

**Comment by Radical-from-Scratch** [comment]
Okay, thank you.
