### ISSUE TITLE
Three Help Glitches

### ISSUE THREAD

**Issue by Radical-from-Scratch** [NoMod-Programming/Whiskers-2.8#7]
1) Clicking operators loads motion.
2) There is no events button.
3) Clicking on variables doesn't show the first two blocks (I know why this is but it's hard to explain)

**Comment by NoMod-Programming** [comment]
Ooh. I'll have to look at that. I might have left something in there from a while back.

**Comment by Radical-from-Scratch** [comment]
I downloaded it from the github repo

**Comment by NoMod-Programming** [comment]
Hmm... I can't reproduce this bug. What OS/Browser are you using?

**Comment by Radical-from-Scratch** [comment]
Windows 10. I'm using Google Chrome, but have no idea why that would matter.

**Comment by NoMod-Programming** [comment]
My bad (I am used to asking that on the Scratch Forums). I'll have to ask one of my friends who has Windows 10 to reproduce it for me. It might be an issue with that.

**Comment by Radical-from-Scratch** [comment]
OK, thanks.

**Comment by Radical-from-Scratch** [comment]
I'm sorry, *Operators* is what loads motion. Pen loads pen. Not sure what the others do. I just assumed that was the case for all them. I'll check with the other categories.

**Comment by NoMod-Programming** [comment]
Alright. I *can* reproduce that issue.

**Comment by Radical-from-Scratch** [comment]
That was totally my fault.

On a side note, please let me know when you are done with your other changes.
