### ISSUE TITLE
Some blocks are red

### ISSUE THREAD

**Issue by Radical-from-Scratch** [NoMod-Programming/Whiskers-2.8#8]
I've checked this up and down, and can't find out why.

But you're a tad better at Squeak than I, perhaps you could take a look?

**Comment by NoMod-Programming** [comment]
Nope. Not a bug. It's to distinguish which blocks are 2.0 blocks and which blocks are original 1.4 blocks. But maybe another way of doing it is in order?

**Comment by Radical-from-Scratch** [comment]
Is that for devving purposes or for the user? If it's for the user, then I say get rid of it. Red blocks look ugly, frown upon our coding abilities, and make the project look like it's a puzzle without the piece in the middle. If it's for *us*, then we could make a "turn all 2.0 blocks PURPLE (purple, not red (well, it doesn't have to be purple, just something that's not red) ) button" to help us.

**Comment by NoMod-Programming** [comment]
Hmm... How about an icon on the block?

**Comment by Radical-from-Scratch** [comment]
I'll look through ScratchSkin and see what'd fit it best.

**Comment by NoMod-Programming** [comment]
Or maybe a new icon. I was thinking somehting like a '2' surrounded by a circle. What do you think of that?

**Comment by Radical-from-Scratch** [comment]
I'd be OK with that. I was also looking at "addItem" and "folderCatIcon". 

If you make the icon, I'll work on hacking them into the block.

I will wait till you finish your changes so they will be easily mergable.

**Comment by Jonathan50** [comment]
@Radical-from-Scratch How does it frown upon your coding abilities?
