### ISSUE TITLE
Sound editor needs a MASSIVE makeover

### ISSUE THREAD

**Issue by Radical-from-Scratch** [NoMod-Programming/Whiskers-2.8#9]
It looks NOTHING like the one on Scratch. Main thing is the buttons and BG colour.

**Comment by NoMod-Programming** [comment]
Alright... I'm gonna have this done for the next release

**Comment by Radical-from-Scratch** [comment]
My recommendation for you is to open up the Flash version and Whiskers side-by-side. That's what I'm gonna do to fix the file menu.

**Comment by NoMod-Programming** [comment]
Yeah. I'm actually doing that right now. It looks like the BG is slightly patterned or something, by looking in the source, so I'm going to try to port that over.

**Comment by Radical-from-Scratch** [comment]
Okay, I will wait til you finish to do my idea then.
